name: Build and deploy #action名称
on:
  push:
    branchs:
      - 'master'
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      # - name: SFTP Sync
      - name: deploy file
        uses: sahilNR/release-upload-sftp@v4
        with:
          package_name: 'demo-package'
          username: 'root'
          server: '${{ secrets.server }}'
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './public'
          remote_path: '/var/action'
        # uses: swillner/sftp-sync-action@v1.0
        # with:
        #   server: ${{secrets.server}}
        #   user: root
        #   user_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
        #   host_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCpcqJBY326kxZE8GiarAmKks4nva4a6RbGY9UCxaw5rcN8Pz7swk51kIiN4SWRRvxIHL6M9X7154TdJ0506EcDWfHc1Z62iO45oFXxnzfN8tVnX48pxn6uzOcJl62YXNy+B2B1BXe/kS9UWdUiJeeizCwM+wMVVcLy6eau2VvBbP6trUxh8sKHZx2Nc95qpI+axI2z9nMQxt3I9ELIOsfLRTllptgLgwvC7z/hsLCvw+r6DbpKuuIP9ixOzZ+U0Fl0IY/0YqMXJW1BlCkCHXQB8bxKD6JDwCcpoz4anU9qb1LGzMGwW6GsuIZ6cYx3TBiI4NapbLe9g7Z6Qhuvky05ngF9B87Cajri/H8P2943KEyV97HRi0q6We4WmaxjZSdcGSLzsLx8ahmDQRmUv1Pi9cHhoX8azxljmsDBHMKJXDrBQmKwdONzMcYbxw0oecI8OheR5VekGz3mF5n85iuo0RmHzBUX5YIvh6JJ8lHrXpJRtLZprOclQXnLOHxSOlk="
        #   remote: /home/root/upload
        #   mirror_options: "--exclude-glob=.git*/ --verbose"