name: Build and deploy
on:
  push:
    branchs:
      - 'master'
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
