name: Build and deploy
on:
  push:
    branchs:
      - 'master'
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.3
        with:
          sftp: false
          host: ${{ secrets.SERVER }}
          port: 21
          username: root
          password: ${{ secrets.PASSWORD }}
          remote_folder: '/var/action'
